[credentials0]
initial_hour = 10
email = jhopkin1@jh.edu
password = Levering123
name = Johns

[credentials1]
initial_hour = 12
email = ianpark8@jh.edu
password = SleepyIan123
name = Ian

[credentials2]
initial_hour = 14
email = sample4@jh.edu
password = Password123!
name = Sample

; etc...
